config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :items, only: [:index, :show]

    resource :customers, only: [:edit, :update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/unsubscribe' => 'customers#unsubscribe'


    delete '/cart_items' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, except: [:edit, :update, :destroy]


    resources :addresses, except: [:new, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def destination
    postal_code + address + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_active == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    "#{last_name} #{first_name}"
  end
  def kana
    "#{last_name_kana} #{first_name_kana}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :oeder_ditails, dependent: :destroy

  belongs_to :genre

  attachment :image

  def tax_price
    (self.price * 1.10 ).round
  end
  
  def subtotal
    amount * tax_price
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_ditails, dependent: :destroy
  belongs_to :customer

  def current_postage
    800
  end

  def destination
    # postal_code + " " + address + " " + name
    "#{postal_code} #{address} #{name}"
  end



  enum payment_method: {
    credit: 0, # クレジットカード
    bank: 1 # 銀行振込
  }

  enum status: {
    waiting: 0, # 入金待ち
    confirmed: 1, # 入金確認
    in_creation: 2, # 製作中
    preparing: 3, # 発送準備中
    delivered: 4 # 発送済
  }

end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

  enum making_status: {
    not_possible: 0, # 製作不可
    waiting: 1, # 製作待ち
    in_creation: 2, # 製作中
    complete: 3 # 製作完了
  }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer)
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id].present?
      @order = Order.where(customer_id: params[:customer_id]).page(params[:page]).per(10).order('id DESC')
    else
      @order = Order.all.page(params[:page]).per(10).order('id DESC')
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item =Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)

    if @order.status == "confirmed"
      @order.order_ditails.each do |order_ditail|
        order_ditail.update(making_status: 1)
      end
    end

    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :total_payment, :postage, :payment_method, :status)
  end



end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/customers/edit.html.erb
<div>
  <div class="my-4">
    <h4 class="information px-5">
      <%= @customer.name %>さんの会員情報編集
    </h4>
  </div>

  <%= form_with model: @customer, url: admin_customer_path(@customer), local: true do |f| %>
  <table class="table table-borderless">
      <tbody>
        <tr>
          <td>会員ID</td>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <td>氏名</td>
          <td><%= f.text_field :last_name, autofocus: true %></td>
          <td><%= f.text_field :first_name %></td>
        </tr>
        <tr>
          <td>フリガナ</td>
          <td><%= f.text_field :last_name_kana, autocomplete: "last_name_kana", placeholder: "レイワ" %></td>
          <td><%= f.text_field :first_name_kana, autocomplete: "first_name_kana", placeholder: "ミチコ" %></td>
        </tr>
        <tr>
          <td>郵便番号</td>
          <td><%= f.number_field :postal_code, autocomplete: "postal_code", placeholder: "0000000" %></td>
        </tr>
        <tr>
          <td>住所</td>
          <td colspan="3"><%= f.text_field :address, autocomplete: "address", placeholder: "東京都渋⾕区代々⽊神園町0-0" %></td>
        </tr>
        <tr>
          <td>電話番号</td>
          <td><%= f.telephone_field :telephone_number, autocomplete: "telephone_number", placeholder: "0000000000" %></td>
        </tr>
        <tr>
          <td>メールアドレス</td>
          <td><%= f.email_field :email, autocomplete: "email", placeholder: "sample@example.com" %></td>
        </tr>
        <tr>
          <td>会員ステータス</td>
          <td>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "有効" %>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "退会" %>
          </td>
        </tr>
        <tr>
          <td></td>
          <td><%= f.submit "変更を保存", class: 'px-5 btn btn-success' %></td>
        </tr>
      </tbody>
    </table>
    <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">会員一覧</h4>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">会員ID</th>
        <th scope="col">氏名</th>
        <th scope="col">メールアドレス</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td><%= link_to customer.name, admin_customer_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <% if customer.is_active == true %>
        <td class="text-secondary">退会</td>
        <% else %>
        <td class="text-success">有効</td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">
      <%= @customer.name %>さんの会員詳細
    </h4>
  </div>

  <table class="table table-borderless">
    <tbody>
      <tr>
        <td>会員ID</td>
        <td><%= @customer.id %></td>
      </tr>
      <tr>
        <td>氏名</td>
        <td><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td>フリガナ</td>
        <td><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td>郵便番号</td>
        <td><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td>住所</td>
        <td colspan="2"><%= @customer.address %></td>
      </tr>
      <tr>
        <td>電話番号</td>
        <td><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td>メールアドレス</td>
        <td><%= @customer.email %></td>
      </tr>
      <tr>
        <td>会員ステータス</td>
        <% if @customer.is_active == true %>
        <td class="text-secondary">退会</td>
        <% else %>
        <td class="text-success">有効</td>
        <% end %>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success" %></td>
        <td><%= link_to "注文履歴を見る", admin_root_path(customer_id: @customer.id), class: "btn btn-primary" %></td>
      </tr>
    </tbody>
  </table>
</div>