config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :items, only: [:index, :show]

    resource :customers, only: [:edit, :update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/unsubscribe' => 'customers#unsubscribe'


    delete '/cart_items' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, except: [:edit, :update, :destroy]


    resources :addresses, except: [:new, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def destination
    postal_code + address + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_active == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    "#{last_name} #{first_name}"
  end
  def kana
    "#{last_name_kana} #{first_name_kana}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :oeder_ditails, dependent: :destroy

  belongs_to :genre

  attachment :image

  def tax_price
    (self.price * 1.10 ).round
  end
  
  def subtotal
    amount * tax_price
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_ditails, dependent: :destroy
  belongs_to :customer

  def current_postage
    800
  end

  def destination
    # postal_code + " " + address + " " + name
    "#{postal_code} #{address} #{name}"
  end



  enum payment_method: {
    credit: 0, # クレジットカード
    bank: 1 # 銀行振込
  }

  enum status: {
    waiting: 0, # 入金待ち
    confirmed: 1, # 入金確認
    in_creation: 2, # 製作中
    preparing: 3, # 発送準備中
    delivered: 4 # 発送済
  }

end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

  enum making_status: {
    not_possible: 0, # 製作不可
    waiting: 1, # 製作待ち
    in_creation: 2, # 製作中
    complete: 3 # 製作完了
  }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id].present?
      @order = Order.where(customer_id: params[:customer_id]).page(params[:page]).per(10).order('id DESC')
    else
      @order = Order.all.page(params[:page]).per(10).order('id DESC')
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item =Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def show
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)

    if @order.status == "confirmed"
      @order.order_ditails.each do |order_ditail|
        order_ditail.update(making_status: 1)
      end
    end

    redirect_to admin_order_path(@order)
  end

  private
  def order_params
    params.require(:order).permit(:customer_id, :postal_code, :address, :name, :total_payment, :postage, :payment_method, :status)
  end



end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_out_path_for(resource)
    admin_session_path
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">ジャンル編集</h4>
  </div>

  <%= form_with model: @genre, url: admin_genre_path, local:true do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row">ジャンル名</th>
          <td><%= f.text_field :name, autofocus: true %></td>
          <td>
            <%= f.submit '変更を保存', class: "btn btn-success" %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">ジャンル一覧・追加</h4>
  </div>

  <%= form_with model: @genre, url: admin_genres_path, local:true do |f| %>
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th scope="row">ジャンル名</th>
          <td><%= f.text_field :name, autofocus: true, placeholder: "ジャンル名" %></td>
          <td>
            <%= f.submit '新規登録', class: "btn btn-success" %>
          </td>
        </tr>
      </tbody>
    </table>
  <% end %>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th>ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @genres.each do |genre| %>
      <tr>
        <td><%= genre.name %></td>
        <td>
          <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">商品編集</h4>
  </div>

  <%= form_with model: @item, url: admin_item_path(@item), local:true do |f| %>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th scope="row">商品画像</th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th scope="row">商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th scope="row">商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th scope="row">ジャンル</th>
        <td><%= f.collection_select :genre_id, @genres, :id, :name %></td>
      </tr>
      <tr>
        <th scope="row">税抜価格</th>
        <td><%= f.number_field :price %>円</td>
      </tr>
      <tr>
        <th scope="row">販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, :true, checked: true %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "販売停止中" %>
        </td>
      </tr>
      <tr>
        <th scope="row"></th>
        <td><%= f.submit '変更を保存', class: "btn btn-success" %></td>
      </tr>
      </tr>
    </tbody>
  </table>
  <% end %>

</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">商品一覧</h4>
    <button type="button" class="btn btn-light shadow active rounded-circle">
      <%= link_to "+", new_admin_item_path, class: 'text-dark' %>
    </button>
  </div>

  <table class="table">
    <thead class="thead-light">
      <tr>
        <th scope="col">商品ID</th>
        <th scope="col">商品名</th>
        <th scope="col">税抜価格</th>
        <th scope="col">ジャンル</th>
        <th scope="col">ステータス</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
      <tr>
        <td><%= item.id %></td>
        <td><%= link_to item.name, admin_item_path(item) %></td>
        <td><%= item.price.to_s(:delimited) %></td>
        <td><%= item.genre.name %></td>
        <% if item.is_active == true %>
        <td class="text-success">販売中</td>
        <% else %>
        <td class="text-secondary">販売停止中</td>
        <% end %>
      </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">商品新規登録</h4>
  </div>

  <%= form_with model: @item, url: admin_items_path, local:true do |f| %>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <th scope="row">商品画像</th>
        <td><%= f.attachment_field :image %></td>
      </tr>
      <tr>
        <th scope="row">商品名</th>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <th scope="row">商品説明</th>
        <td><%= f.text_area :introduction %></td>
      </tr>
      <tr>
        <th scope="row">ジャンル</th>
        <td><%= f.collection_select :genre_id, @genres, :id, :name, { prompt: "--選択してください--" } %></td>
      </tr>
      <tr>
        <th scope="row">税抜価格</th>
        <td><%= f.number_field :price %>円</td>
      </tr>
      <tr>
        <th scope="row">販売ステータス</th>
        <td>
          <%= f.radio_button :is_active, :true, checked: true %>
          <%= f.label :is_active, "販売中" %>
          <%= f.radio_button :is_active, :false %>
          <%= f.label :is_active, "販売停止中" %>
        </td>
      </tr>
      <tr>
        <th></th>
        <td><%= f.submit '新規登録', class: "btn btn-success" %></td>
      </tr>
    </tbody>
  </table>
  <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">商品詳細</h4>
  </div>

  <table class="table table-borderless">
    <tbody>
      <tr>
        <td rowspan="5"><%= attachment_image_tag @item, :image, :fill, 300, 200, format:'jpg', fallback:"no_image.jpg" %></td>
        <td>商品名</td>
        <td colspan="2"><%= @item.name%></td>
      </tr>
      <tr>
        <td>商品説明</td>
        <td colspan="2"><%= @item.introduction %></td>
      </tr>
      <tr>
        <td>ジャンル</td>
        <td ><%= @item.genre.name %></td>
      </tr>
      <tr>
        <td>税込価格<br>(税抜価格)</td>
        <td>
          <%= @item.tax_price.to_s(:delimited) %>
          (<%= @item.price.to_s(:delimited) %>) 円
        </td>
      </tr>
      <tr>
        <td>販売ステータス</td>
        <% if @item.is_active == true %>
        <td class="text-success">販売中</td>
        <% else %>
        <td class="text-secondary">販売停止中</td>
        <% end %>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="my-4">
    <h4 class="information px-5">注文履歴詳細</h4>
  </div>

  <%= form_with model: @order, url: admin_order_path, local: true do |f| %>
  <table class="table table-borderless">
    <tbody>
      <tr>
        <td>購入者</td>
        <td><%= link_to @order.customer.name, admin_root_path(customer_id: @order.customer.id) %></td>
      </tr>
      <tr>
        <td>注文日</td>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td>配送先</td>
        <td><%= @order.destination %></td>
      </tr>
      <tr>
        <td>支払方法</td>
        <td><%= @order.payment_method_i18n %></td>
      </tr>
      <tr>
        <td>注文ステータス</td>
        <td>
          <%= f.select :status, Order.statuses_i18n.invert %>
          <%= f.submit '更新', class: "btn btn-success" %>
        </td>
      </tr>
    </tbody>
  </table>
  <% end %>

  <table class="table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>商品名</th>
        <th>単価(税込)</th>
        <th>数量</th>
        <th>小計</th>
        <th>製作ステータス</th>
      </tr>
    </thead>
    <% @order.order_ditails.each do |order_ditail| %>
    <tbody>
      <tr>
        <td><%= order_ditail.item.name %></td>
        <td><%= order_ditail.tax_price.to_s(:delimited) %></td>
        <td><%= order_ditail.amount %></td>
        <td><%= order_ditail.subtotal.to_s(:delimited) %></td>
        <td>
          <%= form_with model: order_ditail, url: admin_order_detail_path(order_ditail.id), local: true do |f| %>
            <%= f.select :making_status, OrderDitail.making_statuses_i18n.invert%>
            <%= f.submit '更新', class: "btn btn-success" %>
          <% end %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>

  <table class="table table-bordered">
    <tbody>
      <tr>
        <td>商品合計</td>
        <td><%= @order.total_payment.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <td>送料</td>
        <td><%= @order.current_postage.to_s(:delimited) %>円</td>
      </tr>
      <tr>
        <td>請求金額合計</td>
        <td scope="row"><%= (@order.total_payment + @order.current_postage).to_s(:delimited) %>円</td>
      </tr>
    </tbody>
  </table>
</div>