config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    root to: 'homes#top'
    get '/about' => 'homes#about'

    resources :items, only: [:index, :show]

    resource :customers, only: [:edit, :update]
    get '/customers/my_page' => 'customers#show'
    get '/customers/confirm' => 'customers#confirm'
    patch '/customers/unsubscribe' => 'customers#unsubscribe'


    delete '/cart_items' => 'cart_items#destroy_all'
    resources :cart_items, except: [:new, :show, :edit]

    post '/orders/confirm' => 'orders#confirm'
    get '/orders/thanks' => 'orders#thanks'
    resources :orders, except: [:edit, :update, :destroy]


    resources :addresses, except: [:new, :show]
  end

  namespace :admin do
    root to: 'homes#top'

    resources :items, except: [:destroy]
    resources :genres, except: [:new, :show, :destroy]
    resources :customers, except: [:new, :create, :destroy]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  devise_for :customers, :controllers => {
    :sessions => 'public/sessions',
    :registrations => 'public/registrations'
  }

  devise_for :admin, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def destination
    postal_code + address + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  def active_for_authentication?
    super && (self.is_active == false)
  end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  def name
    "#{last_name} #{first_name}"
  end
  def kana
    "#{last_name_kana} #{first_name_kana}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :items, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord

  has_many :cart_items, dependent: :destroy
  has_many :oeder_ditails, dependent: :destroy

  belongs_to :genre

  attachment :image

  def tax_price
    (self.price * 1.10 ).round
  end
  
  def subtotal
    amount * tax_price
  end

end

app/models/order.rb
class Order < ApplicationRecord

  has_many :order_ditails, dependent: :destroy
  belongs_to :customer

  def current_postage
    800
  end

  def destination
    # postal_code + " " + address + " " + name
    "#{postal_code} #{address} #{name}"
  end



  enum payment_method: {
    credit: 0, # クレジットカード
    bank: 1 # 銀行振込
  }

  enum status: {
    waiting: 0, # 入金待ち
    confirmed: 1, # 入金確認
    in_creation: 2, # 製作中
    preparing: 3, # 発送準備中
    delivered: 4 # 発送済
  }

end

app/models/order_ditail.rb
class OrderDitail < ApplicationRecord

  belongs_to :item
  belongs_to :order

  def tax_price
    (self.item.price * 1.10 ).round
  end

  def subtotal
    amount * tax_price
  end

  enum making_status: {
    not_possible: 0, # 製作不可
    waiting: 1, # 製作待ち
    in_creation: 2, # 製作中
    complete: 3 # 製作完了
  }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path(@genre)
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController

  def top
    if params[:customer_id].present?
      @order = Order.where(customer_id: params[:customer_id]).page(params[:page]).per(10).order('id DESC')
    else
      @order = Order.all.page(params[:page]).per(10).order('id DESC')
    end
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item =Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
  
  
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <button type="button" class="btn btn-outline-secondary">
            <%= link_to root_path, class:'font-weight-bold navbar-brand p-3' do %>
              <span>NaganoCake</span>
            <% end %>
          </button>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if customer_signed_in? %>
            <li class="nav-item pt-3 mr-5">
              ようこそ、<%= current_customer.last_name %>さん！
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "マイページ",customers_my_page_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "商品一覧",items_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "カート",cart_items_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "ログアウト", destroy_customer_session_path, class: 'nav-link text-dark', method: :delete %>
                </button>
            </li>
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "会員一覧",admin_customers_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "注文履歴一覧",admin_root_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "ジャンル一覧",admin_genres_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "ログアウト", destroy_admin_session_path, class: 'nav-link text-dark', method: :delete %>
                </button>
            </li>
            <% else %>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "About", about_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "商品一覧", items_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="btn btn-outline-secondary">
                <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
              </button>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main>
      <%= yield %>
    </main>

    <footer class="border-top">
      <div class="container mt-3">
        <div class="row">
          <div class="mx-auto p-2">
            <p>NaganoCake</p>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>